//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanfossTest.WCF.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public System.Guid HouseId { get; set; }
        public Nullable<System.Guid> RefWaterCounter { get; set; }
        public string Address { get; set; }
    
        public virtual WaterCounter WaterCounter { get; set; }
    }
}
